### ISSUE TITLE
The install, usage, contribute seem to be accessible only to IBMers

### ISSUE THREAD

**Issue by gmosx** [carbon-design-system/carbon-icons#10]
How about providing them as simple github/wiki pages?

**Comment by hellobrian** [comment]
Thanks for pointing this out. 
For now, the `master` branch is mirroring our original carbon-icons repo from our GitHub Enterprise at IBM.

Moving forward, all updates I'm making will be reflected in the `6.x` branch including updating docs so that they're visible to public users.

For your initial ask, expect the issue to be resolved by end of this week or earlier.

**Comment by hellobrian** [comment]
all the docs are now using public links. If there are any IBM links that should be made public, feel free to make another issue.
